### ISSUE TITLE
Missing Classes

### ISSUE THREAD

**Issue by Pixchure** [xBrownieCodezV2/Verus-AntiCheat-SourceCode#1]
There are missing classes like Check.java, DataManager.java, PacketCheck.java etc. also theres missing packages

**Comment by xBrownieCodezV2** [comment]
![mDUxMYq](https://user-images.githubusercontent.com/72617433/113522934-d2dff580-95a4-11eb-9070-87680d8273a9.png)
I dont kno where the problem is, it says everywhere that its work in progress.

**Comment by xBrownieCodezV2** [comment]
![FNw4I2k](https://user-images.githubusercontent.com/72617433/113522965-1b97ae80-95a5-11eb-9d3b-f96fa8a0990b.png)

**Comment by vyan911** [comment]
it not work wtf bad

**Comment by ItzRiotz** [comment]
I hope you're joking @vyan911

**Comment by vyan911** [comment]
sex good yes

**Comment by steviebeenz** [comment]
WHERE ARE MY PACKETWRAPPERS? WORST LEAK BY BROWNIE EVER

**Comment by steviebeenz** [comment]
NO SEX
