### ISSUE TITLE
some classes are missing

### ISSUE THREAD

**Issue by iiProCraft** [xBrownieCodezV2/Verus-AntiCheat-SourceCode#4]
some classes like VerusConfiguration are missing.

**Comment by GardeningTool** [comment]
Read the readme.

**Comment by steviebeenz** [comment]
What is the readme tho?

**Comment by GardeningTool** [comment]
> What is the readme tho?

https://github.com/xBrownieCodezV2/Verus-AntiCheat-SourceCode/blob/main/README.md

**Comment by steviebeenz** [comment]
> > What is the readme tho?
> 
> https://github.com/xBrownieCodezV2/Verus-AntiCheat-SourceCode/blob/main/README.md

Oh so you don't appreciate people making fun of idiots who can't read the front page of a github repo? Understandable.

**Comment by GardeningTool** [comment]
> > > What is the readme tho?
> > 
> > 
> > https://github.com/xBrownieCodezV2/Verus-AntiCheat-SourceCode/blob/main/README.md
> 
> Oh so you don't appreciate people making fun of idiots who can't read the front page of a github repo? Understandable.

Lmfao sorry
