### ISSUE TITLE
HELP ME (SERIOUS BYPASS)

### ISSUE THREAD

**Issue by DortDev** [xBrownieCodezV2/Verus-AntiCheat-SourceCode#7]
I INSTALLED THE ANTICHEAT BUT PPL ARE STILL FLYING AT MACH 10

**Comment by GardeningTool** [comment]
Config issue.

**Comment by DortDev** [comment]
LOL

**Comment by GardeningTool** [comment]
Please try using Verus alongside NoCheatPlus. Or just remove Verus from the server, you'll get the same results anyways.
