### ISSUE TITLE
BIG ISSUE WITH VERUS (CRAZY) (SERIOUS) (INSANE) 

### ISSUE THREAD

**Issue by genericcc** [xBrownieCodezV2/Verus-AntiCheat-SourceCode#8]
HELP MY C0F RAN AWAY AND NOW I CAN FLY HAKE PLZ HELPE BRO I SET GROUND STATE TRUE WHAT IS GO ON???? WHY I SEND C13 AND KILLAURA CHECK NO WORK PLEASE HELP MAN I HAVE HIGH PING AND NOW MOVEMENT CHECK NO WORK WHY AM I GETTING HIT

**Comment by GardeningTool** [comment]
Config issue.

**Comment by genericcc** [comment]
> Config issue.

9947 Kirkstone Terrace Drive issue...

**Comment by GardeningTool** [comment]
k.
