### ISSUE TITLE
استخدام وحدة المعالجة المركزية 999٪؟

### ISSUE THREAD

**Issue by GladUrBad** [xBrownieCodezV2/Verus-AntiCheat-SourceCode#9]
مرحبا! wtf cpu عند 100٪ عند الإبلاغ!؟!

فيرس تحطم الخادم؟ لديها استخدام وحدة المعالجة المركزية عالية و Cuboid.java يغتصبها.

يتم تعطيله أسوأ من Kiru AC الذي صنعه Durpy؟ هل يمكن أن يكون Disabler على Verus يعمل أيضًا؟
هو أيضا خروج الغش مثل Kiru ؟؟

**Comment by GardeningTool** [comment]
Config issue.

**Comment by DortDev** [comment]
This is a serious configuration issue, I was told the same, and have adjusted my configuration to stop people from flying at mach 10 and instead allow them to go even faster!
